# Generated by Django 3.2.9 on 2021-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
